#! /bin/sh

sxhkd &
xmodmap ~/.Xmodmap
polybar bar0 &
setxkbmap br

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bpsc config normal_border_color     "#282828"
bspc config focused_border_color    "#928374"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a vlc state=floating
bspc rule -a feh state=floating
